version: "3.9"
networks:
  net1:
    name: net1
    driver: bridge
services:
  server1:
    build: ./Task-1/
    image: server
    container_name: server1
    networks:
      net1:
        aliases:
          - server1
    ports:
      - "5000:5000"
    environment:
      - SERVER_NAME=server1
